[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"

# Remix-specific routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Remix's built assets
[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Handle favicon and other common static files
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
