[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Required for SPAs - handles client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Optional: For API routes if you have them
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
