[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"

# Remix requires special handling for SPA routing
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Remix build assets
[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

# For Remix API routes if you have them
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
